# Generated by Django 4.2.4 on 2023-09-03 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('discuss_about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('category', models.CharField(choices=[('animals', 'Animals'), ('weeding', 'Weeding'), ('birthday', 'Birth Day'), ('nature', 'Nature')], max_length=15)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField()),
            ],
        ),
    ]
