# Generated by Django 4.2.4 on 2023-09-03 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('category', models.CharField(choices=[('animals', 'Animals'), ('weeding', 'Weeding'), ('birthday', 'Birth Day'), ('nature', 'Nature')], max_length=15)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='cars')),
            ],
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
