# Generated by Django 4.2.4 on 2023-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_web', '0002_photo_delete_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='Photos'),
        ),
    ]
